### PR TITLE
ci: Use rpm-specs GitLab CI template.

### PR DESCRIPTION
**Pull request by dewyatt**

### CODE REVIEW

**Comment by dewyatt** [comment]
I'm not sure why gitlab-ci doesn't show up in this PR, I'll have to look into that.

**Comment by ronaldtse** [comment]
@dewyatt are we good to merge here?

**Comment by dewyatt** [comment]
@ronaldtse Yes please

**Review by ronaldtse — APPROVED** [review]
LGTM. Thanks @dewyatt !

**Comment by dewyatt** [comment]
@ronaldtse Looks like the deploy is missing the token. Can you make sure that `GITHUB_API_TOKEN` is still available for this project on GitLab? We may have lost it when we deleted and re-created the repo. We'll need that available for all rpm-spec-* repos on GitLab. (You can also just create a subgroup to contain all the rpm-spec-* repos and then create a single subgroup protected variable)

**Pull request merged**
